clj-commons/pretty

src/io/aviso/nrepl.clj

This commit resolves issue #28. To review, at the moment opening a REPL
logs the following warning: "[WARNING] No nREPL middleware descriptor in
metadata of #'io.aviso.nrepl/pretty-middleware, see
clojure.tools.middleware/set-descriptor!"
In point of fact, they want you to look at
`clojure.tools.nrepl.middleware/set-descriptor!`
At any rate, this commit sets descriptor metadata on
`io.aviso.nrepl/pretty-middleware` so the error stops being thrown.

Add middleware descriptor to `pretty-middleware`

---

src/io/aviso/exception.clj

This is a pretty minor fix, but the *fonts* map in `io.aviso.exceptions` has a typo in the `:omitted-frame` key. One might not even care about this but it turns out it's spelled correctly everywhere else, so we might as well fix it.

[typo] fixing a typo in the fonts map

---

src/io/aviso/binary.clj

Noticed the tests were broken - adding this 2-arity version of write-binary has everything passing again.

Add 2-arity write-binary fcn to satisfy tests

---

src/io/aviso/ansi.clj

Eval doesn't play nicely with AOT - new instances of functions/constants are created every time the namespace is loaded. This means when doing incremental AOT, io.aviso.pretty generates classes whenever it's `require`d, even if it is itself AOTed already.
This switches from `eval` to `defmacro` for the same effect, but better integration with core clojure.
Testing done: `lein test`.

Switch to using macros instead of eval

---

src/io/aviso/exception.clj

In some scenarios it would be useful to turn off default ANSI fonts globally
in environments where it might cause issues (e.g. polluting logs fed to
other systems for storage and not read by human directly but through a
different interface where ANSI characters are rendered incorrectly).

Add possibility to turn off default set of fonts used for exception formatting.

---

src/io/aviso/exception.clj

Retain the sort order of ex-data keys in the printed output if sorting is present in the original data structure (eg: sorted-maps). Does the usual sorting for everything else.

Fix key sorting for sorted-maps

---

CHANGES.md
docs/conf.py
docs/lein-plugin.rst
project.clj
src/io/aviso/exception.clj
src/io/aviso/lein_pretty.clj

Future versions of Leiningen will not support implicit middleware, or will produce warnings.
Fixes #69 
Fixes #68 
This also removes the hook that attempted to install Pretty into the parent Leiningen process ... that never worked, as Leiningen captures and reports exceptions thrown by plugins in its own code that pretty doesn't override.

Use explicitly configured middleware

---

src/io/aviso/exception.clj
test/io/aviso/exception_test.clj

This commit fixes a NullPointerException when the ex-info data map
contains a nil key. It replaces the nil with a string nil so it will
still show up in the output, but doesn't break the string replace
functions.

Fix an NPE when the ex-info map has a nil key

---

src/io/aviso/exception.clj

Clojure 1.11 introduced a update-keys
Without this change, we will see this warn line every time we load the library
> WARNING: update-keys already refers to: #'clojure.core/update-keys in namespace: io.aviso.exception, being replaced by: #'io.aviso.exception/update-keys

Avoid warns in clojure 1.11

---

CHANGES.md
docs/exceptions.rst
project.clj
src/io/aviso/exception.clj
test/demo.clj

This should help prevent interleaving of output when multiple threads simultaneously write exceptions to *out*.

Buffer write-exception output

---

src/clj_commons/ansi.clj

Use Namespace/find to see if nrepl is running, not require

---

src/clj_commons/ansi.clj

This change proposes to replace `Namespace/find` with `clojure.core/find-ns`.
Attempting to run pretty 2.0.1 in babashka yields an error:
```
(Namespace/find sym)
^--- No matching method find found taking 1 args
```
This is introduced in a recent change (https://github.com/clj-commons/pretty/pull/95), the previous version 2.0 works fine. This is because `Namespace/find` is not compiled (probably considered an implementation detail).
But `clojure.core/find-ns` is included and is equivalent
https://github.com/clojure/clojure/blob/38bafca9e76cd6625d8dce5fb6d16b87845c8b9d/src/clj/clojure/core.clj#L4126-L4130

Keep babashka compatibility

---

src/clj_commons/pretty/repl.clj

Ensure that `pretty-pst` always writes to `*err*`

---

.github/workflows/clojure.yml
deps.edn
src/clj_commons/ansi.clj
src/clj_commons/format/binary.clj
src/clj_commons/format/exceptions.clj
src/clj_commons/format/table.clj

It's really important to use _at least three_ dashes.  Also, it turns out codox supports these tables, in this format, as well.

Fix tables in docstrings

---

CHANGES.md
src/io/aviso/exception.clj
src/io/aviso/repl.clj

Add shims to allow org.clj-commons/pretty to be used in place of io.aviso/pretty in the majority of cases

---

CHANGES.md
src/clj_commons/format/exceptions.clj
test/demo.clj
test/playground.clj

This makes it possible to extract, filter, and transform (for output) an arbitrary stack trace, such as from Thread/getStackTrace(), entirely separately from formatting an exception.

Make visible fn's to extract/filter/format stack frames

---

CHANGES.md
src/clj_commons/format/exceptions.clj
test/playground.clj

After demangling strips off the numeric suffix from a Clojure function name, in cases where you have deeply nested anonymous functions (say, because you are using nubank/state-flow) you can with a long name of repeated `/fn/fn/fn..` values; this change reduces those repeats down to `/fn{x14}` (the actual count).

Abbreviated repeated names in a Clojure function name

---

CHANGES.md
src/clj_commons/format/exceptions.clj
test/clj_commons/exception_test.clj

Added `clj-commons.format.exceptions/default-frame-rules` with the defaults for `*default-frame-rules*` 
which makes it much easier to override the rules.
Added function `clj-commons.format.exceptions/format-stack-trace-element` which can be used to convert a Java
StackTraceElement into demangled, readable string, using the same logic used by `format-exception.`

Two small improvements to the clj-commons.format.exceptions namespace

---

.github/workflows/clojure.yml
CHANGES.md
deps.edn
src/clj_commons/ansi.clj
src/clj_commons/pretty/annotations.clj
src/clj_commons/pretty/spec.clj
test/clj_commons/ansi_test.clj
test/clj_commons/binary_test.clj
test/clj_commons/exception_test.clj
test/clj_commons/pretty/annotations_test.clj
test/clj_commons/test_common.clj

These are utilities that could be associated with code that parses any kind of input and wants to produce well formatted output about errors in that code.
In addition, create a `spec` namespace that covers `clj-commons.ansi` and `clj-commons.pretty.annotations`.

New namespace to produce pretty annotations on input lines

---

src/clj_commons/ansi.clj

I ended up reading through the ANSI namespace while tracking down a red herring, and stumbled on this `if` form. The call to `apply-padding` wasn't changing the data, but it would incur some amount of processing overhead that we don't need to do.
Thanks for considering, and let me know if there's anything I need to adjust/modify.

Fix `normalize-and-pad-markup` to skip actually padding

---

CHANGES.md
README.md
src/clj_commons/format/exceptions.clj
test/demo.clj

Hide clojure.core/apply (and related)
